apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.controller.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
spec:
  replicas: {{ .Values.controller.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.controller.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.controller.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.kubernetes }}
      containers:
      - name: controller
        image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
        imagePullPolicy: Always
        args:
        - --controller-name={{ .Values.controller.name }}
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        env:
        - name: CLS_CONTROLLER_PROJECT_ID
          value: "{{ .Values.gcp.projectId }}"
        - name: CLS_CONTROLLER_API_BASE_URL
          value: "{{ .Values.controller.api.baseUrl }}"
        - name: CLS_CONTROLLER_CONTROLLER_NAME
          value: "{{ .Values.controller.name }}"
        - name: CLS_CONTROLLER_EVENTS_SUBSCRIPTION
          value: "{{ .Values.pubsub.subscription }}"
        - name: CLS_CONTROLLER_CONFIG_NAMESPACE
          value: "{{ .Values.controller.namespace }}"
        - name: CLS_CONTROLLER_CONFIG_NAME
          value: "{{ .Values.controller.name }}"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      terminationGracePeriodSeconds: 10